### ISSUE TITLE
Rest interface not ready yet (java.lang.NoClassDefFoundError: com/google/inject/multibindings/Multibinder)

### ISSUE THREAD

**Issue by tim-jones-001** [mike-plummer/graylog-stockmarket#1]
Cloned and ran (oracle java 8 on mac), but got error below.
Generates quotes fine, but rest interface failed to start giving stream of log entries like below:
```
2017-10-05 11:04:19,104 WARN GraylogInstance:106 :  Graylog rest interface not ready yet, rescheduling...
```
```
Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
[WARNING]
java.lang.NoClassDefFoundError: com/google/inject/multibindings/Multibinder
	at org.graylog2.plugin.inject.Graylog2Module.permissionsBinder(Graylog2Module.java:274)
	at org.graylog2.plugin.PluginModule.addPermissions(PluginModule.java:154)
	at org.graylog2.shared.security.SecurityBindings.configure(SecurityBindings.java:26)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60)
	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.inject.multibindings.Multibinder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```
Would be grateful if you could suggest what I might try to get it going successfully

Thanks

Tim

**Comment by mike-plummer** [comment]
Hmm, weird. I wasn't able to replicate your exact issue but I went ahead and updated the example to the latest Spring Boot and Graylog versions. Let me know if those changes fix your problem.

**Comment by mike-plummer** [comment]
Since I haven't heard back I'm going to assume this is resolved.
